---
{{- range $.Values.robots }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: robot-controller-{{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: robot-controller-{{ .name }}
  template:
    metadata:
      labels:
        app: robot-controller-{{ .name }}
    spec:
      containers:
      - image: {{ $.Values.image.repository }}{{ if $.Values.image.tag }}:{{ $.Values.image.tag }}{{ end }}
        imagePullPolicy: Always
        name: robot-controller
        env:
        - name: ROBCO_ROBOT_NAME
          value: "{{ .name }}"
        - name: EWM_LGNUM
          value: "{{ $.Values.envs.ewmlgnum }}"
        - name: CHARGER_LIST
          value: "{{ $.Values.envs.chargerlist }}"
---
apiVersion: v1
kind: Service
metadata:
  name: robot-controller-{{ .name }}
  labels:
    app: robot-controller-{{ .name }}
spec:
  ports:
  - name: metrics
    port: 8765
  selector:
    app: robot-controller-{{ .name }}
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: robot-controller-{{ .name }}
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: robot-controller-{{ .name }}
{{ end }}
