apiVersion: v1
kind: Secret
metadata:
  name: mir-api
type: Opaque
## Usage of 'stringData' field rather than 'data' to leverage automatic base64 en-/decoding 
## (ref. https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually)
stringData:
  mirhost: "{{ .Values.envs.mirhost }}"
  miruser: "{{ .Values.envs.miruser }}"
  mirpswd: "{{ .Values.envs.mirpassword }}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mir-mission-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mir-mission-controller
  template:
    metadata:
      labels:
        app: mir-mission-controller
    spec:
      containers:
      - name: mir-mission-controller
        image: {{ .Values.image.repository }}{{ if .Values.image.tag }}:{{ .Values.image.tag }}{{ end }}
        imagePullPolicy: Always
        env:
        - name: MIR_USER
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: miruser
        - name: MIR_HOST
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirhost
        - name: MIR_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mir-api
              key: mirpswd
        - name: ROBCO_ROBOT_NAME
          value: "{{ .Values.robot.name }}"
        - name: PLC_TROLLEY_ATTACHED
          value: "{{ .Values.envs.plctrolley }}"